AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an ECS Fargate task and service.

Resources:
  # ECS Task Definition
  MyFargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: apdu-mobileap-fargate-task-cf-template-demo-uat
      Cpu: 256  # 0.25 vCPU
      Memory: 512  # 512 MB RAM
      NetworkMode: awsvpc  # Required for Fargate
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::382560948490:role/ecsTaskExecutionRole  # Replace with your IAM Role for ECS task execution
      TaskRoleArn: arn:aws:iam::382560948490:role/ecsTaskRole  # Replace with your IAM Role for task
      ContainerDefinitions:
        - Name: cf-template-demo
          Image: 382560948490.dkr.ecr.ap-southeast-1.amazonaws.com/apdu-mobileap-cf-template-demo-uat:latest  # Replace with your ECR repository URI
          PortMappings:
            - ContainerPort: 80  # Port in the container
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/my-fargate-task  # CloudWatch log group for ECS task logs
              awslogs-region: ap-southeast-1  # Replace with your region
              awslogs-stream-prefix: ecs

  # ECS Fargate Service
  MyFargateService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: apdu-mobileap-fargate-service-cf-template-test-uat
      Cluster: arn:aws:ecs:ap-southeast-1:382560948490:cluster/MyECSCluster  # Replace with your ECS Cluster ARN
      TaskDefinition: !Ref MyFargateTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 2  # Number of tasks to run
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED  # Set to ENABLED for public IP, DISABLED for private IP
          SecurityGroups:
            - sg-xxxxxxxxxxxxxx  # Replace with your security group
          Subnets:
            - subnet-0218462c6b5886d5e  # Replace with your subnet IDs
            - subnet-0af2143fc2d1589d7  # Replace with your subnet IDs
      LoadBalancers:
        - TargetGroupArn: arn:aws:elasticloadbalancing:ap-southeast-1:382560948490:targetgroup/MyTargetGroup/xxxxxxxxxx  # Replace with your Target Group ARN
          ContainerName: my-container  # Same name as in the task definition
          ContainerPort: 80  # Same container port as in task definition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100

Outputs:
  FargateServiceName:
    Description: The name of the ECS Fargate service
    Value: !Ref MyFargateService

  TaskDefinitionArn:
    Description: The ARN of the ECS Fargate task definition
    Value: !Ref MyFargateTaskDefinition
